name = "AWSLambdaRuntimeInterfaceClients"
uuid = "f70b8da9-77fa-4237-9c91-5f7afb4d62ab"
authors = ["goropikari <goropikari56@gmail.com>"]
version = "0.1.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
